
#############################################################################################################
# 定义根的位置
BINPATH = bin
SRCPATH :=source
INCPATH :=include
SRC := $(SCRPATH)/add.c $(SCRPATH)/sub.c $(SCRPATH)/main.c 
TRAGET := test
all := $TRGET
all : $(SRC)
	echo $(SRC)
	gcc $(SRC) -Iinclude/ -o test